/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { Id, IndexName, UserDefinedObject, VersionNumber } from '@_types/common'
import { ErrorCause } from '@_types/Errors'
import { TypeMapping } from '@_types/mapping/TypeMapping'
import { AdditionalProperties } from '@spec_utils/behaviors'
import { Dictionary } from '@spec_utils/Dictionary'
import { Stringified } from '@spec_utils/Stringified'

export class Response {
  body: { docs: SimulateIngestDocumentResult[] }
}

export class SimulateIngestDocumentResult {
  doc?: IngestDocumentSimulation
}

/**
 * The results of ingest simulation on a single document. The _source of the document contains
 * the results after running all pipelines listed in executed_pipelines on the document. The
 * list of executed pipelines is derived from the pipelines that would be executed if this
 * document had been ingested into _index.
 *
 * @behavior_meta AdditionalProperties fieldname=metadata description="Additional metadata"
 */
export class IngestDocumentSimulation
  implements AdditionalProperties<string, string>
{
  /**
   * Identifier for the document.
   */
  _id: Id
  /**
   * Name of the index that the document would be indexed into if this were not a simulation.
   */
  _index: IndexName
  /**
   * JSON body for the document.
   */
  _source: UserDefinedObject
  /**
   *
   */
  _version: Stringified<VersionNumber>
  /**
   * A list of the names of the pipelines executed on this document.
   */
  executed_pipelines: Array<string>
  /**
   * A list of the fields that would be ignored at the indexing step. For example, a field whose
   * value is larger than the allowed limit would make it through all of the pipelines, but
   * would not be indexed into Elasticsearch.
   */
  ignored_fields?: Array<Dictionary<string, string>>
  /**
   * Any error resulting from simulatng ingest on this doc. This can be an error generated by
   * executing a processor, or a mapping validation error when simulating indexing the resulting
   * doc.
   */
  error?: ErrorCause
  effective_mapping?: TypeMapping
}
