method_request: GET /_data_stream/my-data-stream/_settings
alternatives:
  - language: Python
    code: |-
      resp = client.indices.get_data_stream_settings(
          name="my-data-stream",
      )
  - language: JavaScript
    code: |-
      const response = await client.indices.getDataStreamSettings({
        name: "my-data-stream",
      });
  - language: Ruby
    code: |-
      response = client.indices.get_data_stream_settings(
        name: "my-data-stream"
      )
  - language: PHP
    code: |-
      $resp = $client->indices()->getDataStreamSettings([
          "name" => "my-data-stream",
      ]);
  - language: curl
    code: 'curl -X GET -H "Authorization: ApiKey $ELASTIC_API_KEY" "$ELASTICSEARCH_URL/_data_stream/my-data-stream/_settings"'
