/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { AliasDefinition } from '@indices/_types/AliasDefinition'
import { IndexSettings } from '@indices/_types/IndexSettings'
import { IndexState } from '@indices/_types/IndexState'
import { Dictionary } from '@spec_utils/Dictionary'
import { RequestBase } from '@_types/Base'
import { Metadata, Name, VersionNumber } from '@_types/common'
import { TypeMapping } from '@_types/mapping/TypeMapping'
import { Duration } from '@_types/Time'

/**
 * @rest_spec_name cluster.put_component_template
 * @availability stack since=7.8.0 stability=stable
 * @doc_id indices-component-template
 */
export interface Request extends RequestBase {
  path_parts: {
    name: Name
  }
  query_parameters: {
    /** @server_default false */
    create?: boolean
    /** @server_default 30s */
    master_timeout?: Duration
  }
  body: {
    /**
     * The template to be applied which includes mappings, settings, or aliases configuration.
     */
    template: IndexState
    /**
     * Version number used to manage component templates externally.
     * This number isn't automatically generated or incremented by Elasticsearch.
     */
    version?: VersionNumber
    /**
     * Optional user metadata about the component template.
     * May have any contents. This map is not automatically generated by Elasticsearch.
     * @doc_id mapping-meta-field
     */
    _meta?: Metadata
    /**
     * This setting overrides the value of the `action.auto_create_index` cluster setting.
     * If set to `true` in a template, then indices can be automatically created using that
     * template even if auto-creation of indices is disabled via `actions.auto_create_index`.
     * If set to `false` then data streams matching the template must always be explicitly created.
     */
    allow_auto_create?: boolean
  }
}
