---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elasticsearch-specification

spec:
  type: library
  owner: group:devtools-team
  lifecycle: beta

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kibana-type-checks-pipeline
  description: Run Kibana type checks against the specification

spec:
  type: buildkite-pipeline
  owner: group:devtools-team
  system: buildkite

  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: Kibana type checks
    spec:
      repository: elastic/elasticsearch-specification
      pipeline_file: .buildkite/kibana.yml
      provider_settings:
        trigger_mode: none
      teams:
        devtools-team:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
      schedules:
        Daily main:
          branch: 'main'
          cronline: '0 4 * * *'
          message: 'Daily run for main branch'
