# summary: search-application/apis/get-search-application.asciidoc:95
description: A sucessful response from `GET _application/search_application/my-app/`.
# type: response
# response_code: 200
value:
  "{\n  \"name\": \"my-app\",\n  \"indices\": [ \"index1\", \"index2\" ],\n \
  \ \"updated_at_millis\": 1682105622204,\n  \"template\": {\n    \"script\": {\n\
  \      \"source\": {\n        \"query\": {\n          \"query_string\": {\n    \
  \        \"query\": \"{{query_string}}\",\n            \"default_field\": \"{{default_field}}\"\
  \n          }\n        }\n      },\n      \"lang\": \"mustache\",\n      \"options\"\
  : {\n        \"content_type\": \"application/json;charset=utf-8\"\n      },\n  \
  \    \"params\": {\n        \"query_string\": \"*\",\n        \"default_field\"\
  : \"*\"\n      }\n    }\n  }\n}"
