summary: Change data stream settings on a data stream
description: >
  This shows a response to `PUT /_data_stream/my-data-stream/_settings` when two settings are successfully updated on
  the data stream. In this case, `index.number_of_shards` is only applied to the data stream -- it will be applied to
  the write index on rollover. The setting `index.lifecycle.name` is applied to the data stream and all backing indices.
# type: response
# response_code: 200
value: |-
  {
    "data_streams": [
      {
        "name": "my-data-stream",
        "applied_to_data_stream": true,
        "settings": {
          "index": {
            "lifecycle": {
              "name": "new-test-policy"
            },
            "number_of_shards": "11"
          }
        },
        "effective_settings": {
          "index": {
            "lifecycle": {
              "name": "new-test-policy"
            },
            "mode": "standard",
            "number_of_shards": "11",
            "number_of_replicas": "0"
          }
        },
        "index_settings_results": {
          "applied_to_data_stream_only": [
            "index.number_of_shards"
          ],
          "applied_to_data_stream_and_backing_indices": [
            "index.lifecycle.name"
          ]
        }
      }
    ]
  }
