summary: Attempt to change a data stream setting that is not allowed
description: >
  This shows a response to `PUT /_data_stream/my-data-stream/_settings` when a user attempts to set a setting that is
  not allowed on a data stream. As a result, no change was applied to the data stream.
# type: response
# response_code: 200
value: |-
  {
    "data_streams": [
      {
        "name": "my-data-stream",
        "applied_to_data_stream": false,
        "error": "Cannot set the following settings on a data stream: [index.number_of_replicas]",
        "settings": {},
        "effective_settings": {},
        "index_settings_results": {
          "applied_to_data_stream_only": [],
          "applied_to_data_stream_and_backing_indices": []
        }
      }
    ]
  }
