# Overlays that are specific to the Elasticsearch OpenAPI document
overlay: 1.0.0
info:
  title: Overlays for the Elasticsearch OpenAPI document
  version: 0.0.1
actions:
# Add document info details
  - target: '$.info'
    description: Add a document description and feedback link
    update:
      x-doc-license:
        name: Attribution-NonCommercial-NoDerivatives 4.0 International
        url: 'https://creativecommons.org/licenses/by-nc-nd/4.0/'
      x-feedbackLink:
        label: Feedback
        url: https://github.com/elastic/docs-content/issues/new?assignees=&labels=feedback%2Ccommunity&projects=&template=api-feedback.yaml&title=%5BFeedback%5D%3A+
# Abbreviate and annotate items that are not shown in Bump.sh due to depth limits
  - target: "$.components['schemas']['_types.aggregations.RandomSamplerAggregation']"
    description: Add x-model
    update:
      x-model: true
# Remove long lists of enum values
  - target: "$.components['schemas']['cat._types.CatNodeColumn'].anyOf"
    description: Remove anyOf from cat nodes
    remove: true
  - target: "$.components['schemas']['cat._types.CatNodeColumn']"
    description: Add basic string data type for cat node columns
    update:
      type: string