# summary: search-application/apis/list-search-applications.asciidoc:108
description: A succesful response from `GET _application/search_application?from=0&size=3&q=app*` returns the first three search applications whose names start with `app`.
# type: response
# response_code: 200
value:
  "{\n  \"count\": 2,\n  \"results\": [\n    {\n      \"name\": \"app-1\",\n\
  \      \"updated_at_millis\": 1690981129366\n    },\n    {\n      \"name\": \"app-2\"\
  ,\n      \"updated_at_millis\": 1691501823939\n    }\n  ]\n}"
