method_request: POST _ml/trained_models/elastic__distilbert-base-uncased-finetuned-conll03-english/deployment/cache/_clear
alternatives:
  - language: Python
    code: |-
      resp = client.ml.clear_trained_model_deployment_cache(
          model_id="elastic__distilbert-base-uncased-finetuned-conll03-english",
      )
  - language: JavaScript
    code: |-
      const response = await client.ml.clearTrainedModelDeploymentCache({
        model_id: "elastic__distilbert-base-uncased-finetuned-conll03-english",
      });
  - language: Ruby
    code: |-
      response = client.ml.clear_trained_model_deployment_cache(
        model_id: "elastic__distilbert-base-uncased-finetuned-conll03-english"
      )
  - language: PHP
    code: |-
      $resp = $client->ml()->clearTrainedModelDeploymentCache([
          "model_id" => "elastic__distilbert-base-uncased-finetuned-conll03-english",
      ]);
  - language: curl
    code: 'curl -X POST -H "Authorization: ApiKey $ELASTIC_API_KEY"
      "$ELASTICSEARCH_URL/_ml/trained_models/elastic__distilbert-base-uncased-finetuned-conll03-english/deployment/cache/_clear"'
  - language: Java
    code: |
      client.ml().clearTrainedModelDeploymentCache(c -> c
          .modelId("elastic__distilbert-base-uncased-finetuned-conll03-english")
      );
