[package]
name = "clients_schema"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = {version = "1.0", features=["derive"]}
serde_json = "1.0"
typed-builder = "0.11"
once_cell = "1.16"
anyhow = "1.0"

[dev-dependencies]
serde_path_to_error = "0.1"
serde_ignored = "0.1"
