method_request: GET _tasks?detailed=true&actions=*/delete/byquery
alternatives:
  - language: Python
    code: |-
      resp = client.tasks.list(
          detailed=True,
          actions="*/delete/byquery",
      )
  - language: JavaScript
    code: |-
      const response = await client.tasks.list({
        detailed: "true",
        actions: "*/delete/byquery",
      });
  - language: Ruby
    code: |-
      response = client.tasks.list(
        detailed: "true",
        actions: "*/delete/byquery"
      )
  - language: PHP
    code: |-
      $resp = $client->tasks()->list([
          "detailed" => "true",
          "actions" => "*/delete/byquery",
      ]);
  - language: curl
    code: 'curl -X GET -H "Authorization: ApiKey $ELASTIC_API_KEY" "$ELASTICSEARCH_URL/_tasks?detailed=true&actions=*/delete/byquery"'
