class FollowIndexShardStats {
  bytes_read: long
  failed_read_requests: long
  failed_write_requests: long
  fatal_exception: ErrorCause
  follower_aliases_version: long
  follower_global_checkpoint: long
  follower_index: string
  follower_mapping_version: long
  follower_max_seq_no: long
  follower_settings_version: long
  last_requested_seq_no: long
  leader_global_checkpoint: long
  leader_index: string
  leader_max_seq_no: long
  operations_read: long
  operations_written: long
  outstanding_read_requests: integer
  outstanding_write_requests: integer
  read_exceptions: FollowIndexReadException[]
  remote_cluster: string
  shard_id: integer
  successful_read_requests: long
  successful_write_requests: long
  time_since_last_read_millis: long
  total_read_remote_exec_time_millis: long
  total_read_time_millis: long
  total_write_time_millis: long
  write_buffer_operation_count: long
  write_buffer_size_in_bytes: long
}
