# summary:
# method_request: POST _application/search_application/my-app/_render_query
# description:
# type: request
value:
  params:
    query_string: my first query
    text_fields:
      - name: title
        boost: 5
      - name: description
        boost: 1
