/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { RequestBase } from '@_types/Base'
import { Id, MediaType, Metadata, VersionNumber } from '@_types/common'
import { Duration } from '@_types/Time'
import { ProcessorContainer } from '@ingest/_types/Processors'

/**
 * Create or update a pipeline.
 * Changes made using this API take effect immediately.
 * @doc_id ingest
 * @rest_spec_name ingest.put_pipeline
 * @availability stack since=5.0.0 stability=stable
 * @availability serverless stability=stable visibility=public
 * @ext_doc_id ingest
 */
export interface Request extends RequestBase {
  urls: [
    {
      path: '/_ingest/pipeline/{id}'
      methods: ['PUT']
    }
  ]
  path_parts: {
    /**
     * ID of the ingest pipeline to create or update.
     */
    id: Id
  }
  request_media_type: MediaType.Json
  response_media_type: MediaType.Json
  query_parameters: {
    /**
     * Period to wait for a connection to the master node. If no response is received before the timeout expires, the request fails and returns an error.
     * @server_default 30s
     */
    master_timeout?: Duration
    /**
     * Period to wait for a response. If no response is received before the timeout expires, the request fails and returns an error.
     * @server_default 30s */
    timeout?: Duration
    /**
     * Required version for optimistic concurrency control for pipeline updates
     */
    if_version?: VersionNumber
  }
  body: {
    /**
     * Optional metadata about the ingest pipeline. May have any contents. This map is not automatically generated by Elasticsearch.
     */
    _meta?: Metadata
    /**
     * Description of the ingest pipeline.
     */
    description?: string
    /**
     * Processors to run immediately after a processor failure. Each processor supports a processor-level `on_failure` value. If a processor without an `on_failure` value fails, Elasticsearch uses this pipeline-level parameter as a fallback. The processors in this parameter run sequentially in the order specified. Elasticsearch will not attempt to run the pipeline's remaining processors.
     */
    on_failure?: ProcessorContainer[]
    /**
     * Processors used to perform transformations on documents before indexing. Processors run sequentially in the order specified.
     */
    processors?: ProcessorContainer[]
    /**
     * Version number used by external systems to track ingest pipelines. This parameter is intended for external systems only. Elasticsearch does not use or validate pipeline version numbers.
     */
    version?: VersionNumber
    /**
     * Marks this ingest pipeline as deprecated.
     * When a deprecated ingest pipeline is referenced as the default or final pipeline when creating or updating a non-deprecated index template, Elasticsearch will emit a deprecation warning.
     * @server_default false
     */
    deprecated?: boolean
  }
}
