/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { ProcessorContainer } from '@ingest/_types/Processors'
import { RequestBase } from '@_types/Base'
import { Id, VersionNumber, Metadata } from '@_types/common'
import { Time } from '@_types/Time'

/**
 * @rest_spec_name ingest.put_pipeline
 * @since 5.0.0
 * @stability stable
 */
export interface Request extends RequestBase {
  path_parts: {
    id: Id
  }
  query_parameters: {
    /**
     * Period to wait for a connection to the master node. If no response is received before the timeout expires, the request fails and returns an error.
     * @server_default 30s
     */
    master_timeout?: Time
    /** @server_default 30s */
    timeout?: Time
  }
  body: {
    /**
     * Optional metadata about the ingest pipeline. May have any contents. This map is not automatically generated by Elasticsearch.
     */
    _meta?: Metadata
    /**
     * Description of the ingest pipeline.
     */
    description?: string
    on_failure?: ProcessorContainer[]
    processors?: ProcessorContainer[]
    version?: VersionNumber
  }
}
