name: Check

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

permissions:
  pull-requests: "read"

jobs:
  check-backport-label:
    name: backport label 
    runs-on: ubuntu-latest

    steps:
      - name: "Check backport label"
        if: "!contains(github.event.pull_request.labels.*.name, 'backport')"
        run: |
          echo "Please apply a backport label, or "skip-backport" if no backport is needed"
          echo "Current labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}"
          echo "${{ contains(github.event.pull_request.labels.*.name, 'backport') }}"
          echo "${{ endsWith(github.event.pull_request.labels.*.name, 'backport') }}"
          echo "${{ startsWith(github.event.pull_request.labels.*.name, 'backport') }}"
          echo "${{ github.event.pull_request.labels.*.name == 'skip-backport') }}"
          exit 1
