name: Check output freshness

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install
      run: |
        npm install --prefix compiler
        npm install --prefix typescript-generator

    - name: Generate output
      run: |
        make generate
        npm run start --prefix typescript-generator

    - name: Validate TS output
      run: |
        npm run validate-ts-view --prefix compiler

    - name: Check freshness
      run: |
        if [ -n "$(git status --porcelain)" ]; then echo Error: changes found after running the generation; git diff; git status; exit 1; fi
