name: Update model info

on:
  push:
    branches:
      - "main"
      - "7.*"
    paths:
      - 'specification/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install
      run: |
        npm install --prefix compiler

    - name: Update model info
      run: |
        npm run generate-schema --prefix compiler

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update model info
        push_options: --force-with-lease
        file_pattern: output/schema/schema.json

