summary: Change a data stream setting
method_request: PUT /_data_stream/my-data-stream/_settings
description: >
  This is a request to change two settings on a data stream.
# type: request
value: |-
  {
    "index.lifecycle.name" : "new-test-policy",
    "index.number_of_shards": 11
  }
alternatives:
  - language: Python
    code: |-
      resp = client.indices.put_data_stream_settings(
          name="my-data-stream",
          settings={
              "index.lifecycle.name": "new-test-policy",
              "index.number_of_shards": 11
          },
      )
  - language: JavaScript
    code: |-
      const response = await client.indices.putDataStreamSettings({
        name: "my-data-stream",
        settings: {
          "index.lifecycle.name": "new-test-policy",
          "index.number_of_shards": 11,
        },
      });
  - language: Ruby
    code: |-
      response = client.indices.put_data_stream_settings(
        name: "my-data-stream",
        body: {
          "index.lifecycle.name": "new-test-policy",
          "index.number_of_shards": 11
        }
      )
  - language: PHP
    code: |-
      $resp = $client->indices()->putDataStreamSettings([
          "name" => "my-data-stream",
          "body" => [
              "index.lifecycle.name" => "new-test-policy",
              "index.number_of_shards" => 11,
          ],
      ]);
  - language: curl
    code:
      'curl -X PUT -H "Authorization: ApiKey $ELASTIC_API_KEY" -H "Content-Type: application/json" -d
      ''{"index.lifecycle.name":"new-test-policy","index.number_of_shards":11}''
      "$ELASTICSEARCH_URL/_data_stream/my-data-stream/_settings"'
