summary: Change a data stream setting
method_request: PUT /_data_stream/my-data-stream/_settings
description: >
  This is a request to change two settings on a data stream.
# type: request
value: |-
  {
    "index.lifecycle.name" : "new-test-policy",
    "index.number_of_shards": 11
  }
